In [46]:
import numpy as np 

A = np.array([[1,2,3],
              [4,5,6]])

B = np.array([[6,5,4],
              [3,2,1]])


In [47]:
C = A + B
print('la suma es: \n', C)

print('la resta es: \n',A-B)


la suma es: 
 [[7 7 7]
 [7 7 7]]
la resta es: 
 [[-5 -3 -1]
 [ 1  3  5]]


In [48]:
E = A*B 
print('multiplicacion elemento a elemento \n',E)

multiplicacion elemento a elemento 
 [[ 6 10 12]
 [12 10  6]]


In [49]:
A.dtype

dtype('int64')

In [50]:
a = np.array([[1,2],
              [3,4]])

b= np.array([[5,6],
             [7,8]])

#multiplicocion de matrices AL(Algebra Lineal)
c = np.dot(a,b)
print('la multiplicacion de matrices AL\n',c)
d = a @ b 
print('la multiplicacion de matrices AL\n',d)



la multiplicacion de matrices AL
 [[19 22]
 [43 50]]
la multiplicacion de matrices AL
 [[19 22]
 [43 50]]


In [51]:
#para obtener la transpuesta de una matriz 
f = np.array([[1,2],
              [3,4]])
g = f.T 

print('matriz original \n',f)
print('matriz transpuesta \n',g)

det = np.linalg.det(f)
print('el determinante de la matriz es >> ',det)

h = np.array([[1,2],
              [2,4]])
det_h = np.linalg.det(h)
print('el determinante de la matriz h es >> ',det_h)

#para obtener la inversa de una matriz se usa linalg.inv
#inv = np.linalg.inv(h)
#print('la inversa de la matriz h es >> \n',inv)

matriz original 
 [[1 2]
 [3 4]]
matriz transpuesta 
 [[1 3]
 [2 4]]
el determinante de la matriz es >>  -2.0000000000000004
el determinante de la matriz h es >>  0.0


In [52]:
#vector 
data  =np.arange(1,13)
print('vector \n',data)

#reshape reescribe el vector en una matriz
M = data.reshape(3,4)
print('Matriz 3x4 \n',M)




vector 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Matriz 3x4 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [53]:
#Matriz identidad 
I = np.eye(4)
print('Matriz identidad \n',I)

Matriz identidad 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [54]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

#Suamar todos lo elementos de la matriz 
suma_total = np.sum(A)
print('La suma de los elementos de A es >>',suma_total)

#sumar por filas 
suma_filas = np.sum(A, axis = 1)
print('La suma por filas es >>',suma_filas)

#suma por columnas 
sum_col = np.sum(A,axis = 0 )
print('la suma por columnas es >>',sum_col)

La suma de los elementos de A es >> 45
La suma por filas es >> [ 6 15 24]
la suma por columnas es >> [12 15 18]


In [55]:
#para calular el promedio np.mean(matriz)
print('promedio de todos los elemtos >>',np.mean(A))

#para calular el promedio por fila np.mean(matriz, axis = 1)
print('promedio de todos los elemtos >>',np.mean(A,axis = 1))

#para calular el promedio por columna np.mean(matriz, axis = 0)
print('promedio de todos los elemtos >>',np.mean(A,axis = 0 ))

promedio de todos los elemtos >> 5.0
promedio de todos los elemtos >> [2. 5. 8.]
promedio de todos los elemtos >> [4. 5. 6.]


In [ ]:
# nm.median(matriz) para la mediana 
# nm.std(matriz) para la desviacion estandar 


In [57]:
#matriz de ceros 
W = np.zeros((3,4))
print('matriz de ceros \n',W)

#matriz de unos
G = np.ones((2,3)) 
P = np.ones(4)
print ('vector de unos >>',P)
print('matriz de unos \n',G)



matriz de ceros 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
vector de unos >> [1. 1. 1. 1.]
matriz de unos 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [70]:
V  = np.array([10,20,30,40,50])
print( V[0:4],'\n',V[-1],'\n',V[-3:-1])

#reemplazar valor en el vector 
V[2] = 99
print(V)

[10 20 30 40] 
 50 
 [30 40]
[10 20 99 40 50]


In [91]:
             # 0 1 2
R = np.array([[1,2,3], # 0
              [4,5,6], # 1 
              [7,8,9]])# 2

print(R[0,0],'\n',R[1,2],'\n',R[0])

#imprime ultima columna 
print(R[ :,-1],'\n')

N = M[0:2, 1:3]
print(N),'\n'

print('\n',R[:, [0,2]])


1 
 6 
 [1 2 3]
[3 6 9] 

[[2 3]
 [6 7]]

 [[1 3]
 [4 6]
 [7 9]]


In [ ]:
Q = np.array([[3,7,1],
              [9,2,6],
              [5,4,8]])

#condicion de busqueda 
mascara = Q > 5
print('Matriz mascar \n',mascara)

Matriz mascar 
 [[False  True False]
 [ True False  True]
 [False False  True]]


In [82]:
#Seleccion de datos con mascara 
print(Q[mascara])

[7 9 6 8]


In [86]:
# como modificar toda una fila o columna 
Q[:,0] = 0  #Fila
Q[1,:] = 99 # columna
print('matriz modificada \n',Q)

Q[Q > 50] = 50
print('\n',Q)

matriz modificada 
 [[ 0  7  1]
 [99 99 99]
 [ 0  4  8]]

 [[ 0  7  1]
 [50 50 50]
 [ 0  4  8]]


Nota - para crear una copia de la matrzi no se puede usar A = B
en su lugar se usa .copy

In [ ]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

B = A.copy() 

Z = np.array([10,20,30])
print(Z,'\n')

# crear un vector nuevo añadiendo un elemento  
Z1 = np.append(Z,40)  
print(Z1,'\n')

# agregar mas de un elemento 
Z2 = np.append(Z,[50,60,70])
print(Z2)

In [99]:
J = np.array([[1,2,3],
              [4,5,6]])
#para agragr una fila a la matriz 
# tiene que coincidir con el numero de filas 
nueva_fila = np.array([[1,2,3]])

J1 = np.append(J,nueva_fila, axis = 0 )
print (J1,'\n')

#borrar elemento 
J3 = np.delete(J,1,axis = 0)
print (J3)

[[1 2 3]
 [4 5 6]
 [1 2 3]] 

[[1 2 3]]
