In [17]:
import numpy as np 
import pandas as pd 



In [20]:
# este es el ejemplo de una matriz 
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
B = np.array([[1,0,0],
              [0,1,0],
              [0,0,1]])

C = np.subtract(A,B)
print(C)
a = np.random.normal(size=1000,loc=50,scale=0.2)
print(a)

#print ("Hola mundo")

[[0 2 3]
 [4 4 6]
 [7 8 8]]
[49.91013935 49.9639405  50.08431506 50.16310896 50.37893442 50.08601554
 50.14742109 50.30242444 50.19068657 50.12887847 50.22256215 49.97899597
 50.04536984 49.56592689 50.32954752 50.0749285  50.32787641 49.94380379
 49.90438425 49.97880611 50.05858349 49.90001622 49.92211609 49.90169133
 50.35272941 50.17972822 50.0295459  49.92410499 50.34315337 49.78897403
 50.08545465 49.94172792 50.27316605 49.84092086 49.64431873 49.96228457
 49.93091753 50.0050312  49.80115843 50.25744262 50.04882255 50.22224104
 50.11934221 49.63193656 49.78774176 50.24389479 49.94176053 50.22837492
 50.1278784  50.03824444 49.93343452 50.06061625 49.91199803 49.88585979
 49.65569265 50.3080396  49.85276519 49.7106555  49.87049219 49.99297251
 49.67360648 49.79498032 49.78037238 50.33936525 50.06554212 49.96716488
 49.70131166 49.77890624 49.90891822 50.44085368 49.85634454 50.02597475
 50.28688236 49.89645081 49.93248813 49.95814299 49.68610965 50.3198449
 49.97923672 50.28094799